"""Make program_id NOT NULL in courses table

Revision ID: 5e68defabfef
Revises: ed6a3855de05
Create Date: 2025-07-20 05:11:23.325313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e68defabfef'
down_revision: Union[str, Sequence[str], None] = 'ed6a3855de05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'program_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courses', 'program_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
