"""Update user model: remove fedpoffa_id, make matric_number required

Revision ID: 7cbb583c3c7a
Revises: b11dc701cf62
Create Date: 2025-07-19 15:59:02.763095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbb583c3c7a'
down_revision: Union[str, Sequence[str], None] = 'b11dc701cf62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'matric_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_index(op.f('ix_users_fedpoffa_id'), table_name='users')
    op.drop_column('users', 'fedpoffa_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fedpoffa_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_fedpoffa_id'), 'users', ['fedpoffa_id'], unique=True)
    op.alter_column('users', 'matric_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
