"""update_department_hod_to_user_reference

Revision ID: e2a0a27cd046
Revises: 5e68defabfef
Create Date: 2025-07-21 01:35:46.336566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a0a27cd046'
down_revision: Union[str, Sequence[str], None] = '5e68defabfef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('hod_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['hod_id'], ['id'])
    op.drop_column('departments', 'hod_name')
    op.drop_column('departments', 'hod_email')
    op.drop_column('departments', 'hod_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('hod_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('departments', sa.Column('hod_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('departments', sa.Column('hod_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'hod_id')
    # ### end Alembic commands ###
